### ISSUE TITLE
 你可以发布你用来安装莫哈韦或高塞拉利昂的EFI吗？我在使用EFI安装系统时遇到了麻烦。我有完全相同的笔记本电脑

### ISSUE THREAD

**Issue by BrunoGM** [xzhih/dell-7460-7560-hackintosh#11]

**Comment by xzhih** [comment]
仓库里的 10.14 用不了吗？如果不能安装，可以尝试修改 BIOS 的 dvmt

**Comment by BrunoGM** [comment]
不，我无法使用10.14 EFI，因为它在安装过程中重新启动。
IntelGraphicsDVMTFixup.kext已经在kexts文件夹中。难道这不足以修补DVMT吗？您的笔记本电脑是否有BIOS修改的DVMT？

**Comment by xzhih** [comment]
这就是我觉得奇怪的地方，我用 IntelGraphicsDVMTFixup.kext 来修复 DVMT，并且没有遇到问题，但是除了你之外的其他人也遇到了不能修复的情况

**Comment by EcrosoftXiao** [comment]
我用这个EFI安装10.14遇见了同样的问题，现在解决了
首先勾选inject-intel注入ig-platform 0x12345678开机
然后参照下面的帖子将SLE下的AppleIntelKBLGraphicsFramebuffer.kext打上二进制补丁
[http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1789538&highlight=dvmt](url)
然后在去掉注入的ig-paltform即可
