### ISSUE TITLE
Cpu package idling at 1.5W - Cpu封装闲置在1.5W

### ISSUE THREAD

**Issue by BrunoGM** [xzhih/dell-7460-7560-hackintosh#13]
I saw some EFIs that idle at 0.5-0.7w, the battery life increases a lot with those EFIs. Is your system idling with 1.5w too? I'm using your 10.13 EFI file. - 
我看到一些EFI闲置在0.5-0.7w，电池寿命大大增加这些EFIs。你的系统是否也是1.5瓦空转？我正在使用您的10.13 EFI文件。
我能用英文提问吗？谢谢

**Comment by xzhih** [comment]
Using [Intel® Power Gadget](https://software.intel.com/en-us/articles/intel-power-gadget-20) to Check CPU Frequency is Normal. If the cpu frequency stays high, it will consume a lot of battery.

Battery life is related to battery capacity, Dell 7460 battery is not very large.

Which EFI do you mean? Can I refer to it?

**Comment by BrunoGM** [comment]
Yes, it's the EFI in the #1 post: https://www.tonymacx86.com/threads/guide-dell-inspiron-7560-high-sierra-installation.242174/

Inside his EFI there is a file called SSDT-9-SgUlt.aml inside ACPI/patched. You can copy this file e put it your own EFI's ACPI/patched folder and you will have the 0.5-0.7w idle power consuption. This worked for me.

**Comment by xzhih** [comment]
Thanks for your advice, I solved it now

The new way to disable the Nvidia graphics device seems to be wrong, since [9c74fb3](https://github.com/xzhih/dell-7460-7560-hackintosh/tree/9c74fb341f3b86660f5f8433032d148e8234d079), It just looks like be disabled, and consumes a lot of electricity.

I rollback `SSDT-DDGPU.aml`, Nvidia is truly disabled now, you can try the new EFI.

If you want to learn Chinese, you can join QQ group 158976808

**Comment by BrunoGM** [comment]
Thanks a lot, power management is working perfectly now, even after wakeup(which wasn't with other EFIs I was testing). There's still one minor problem, my brightness is not saving after shutdown. Is this common of the EFI?

**Comment by xzhih** [comment]
Install the latest clover pkg, download from [here](https://github.com/Dids/clover-builder/releases)

![Imgur](https://i.imgur.com/JUDsS1p.png)

With these two items.

reboot, and you will get brightness saving.

**Comment by BrunoGM** [comment]
My system freezes in the middle of the boot if I install the clover pkg. Verbose mode freezes before giving any error.

**Comment by xzhih** [comment]
try old versions

**Comment by rbs7** [comment]
EmuVariableUefi is really necessary? My nvram is correctly being saved without this. Brightness is always loaded correctly. Mine is a Dell 7472.

**Comment by xzhih** [comment]
Depends on device, it is a general plan, I try to make brightness loaded to most people, you don't need it, just delete.

Hope you enjoy your time!
