### ISSUE TITLE
On model Inspiron 7560 intel hd 620 7mb

### ISSUE THREAD

**Issue by iagorm** [xzhih/dell-7460-7560-hackintosh#15]
The graphics is not accelerated, I followed the readme, used the EFI folder of 10.13 which is the same version I use in hackintosh, still disabled.

I installed whole kexts on S/L/E, with no effect, trackpad and keyboard is working, also sound with 13 id, and the battery management is working and showing percentage.

please help me to run this CPU graphics.

**Comment by xzhih** [comment]
I recommend that you re-install MacOS completely.

Do not modify system files, no need to install kexts on S/L/E.

**Comment by iagorm** [comment]
do you recommend a source where I can download the High Sierra?

**Comment by iagorm** [comment]
I re-installed but was needed to add kexts to L/E. And yet the graphics still on 7mb.

**Comment by xzhih** [comment]
This is guide: https://zhih.me/hackintosh-install-guide/

This is source: [mega](https://mega.nz/#!B5kxmZgb!yP3SDWns61V82WHElF7hJvxvapGjNkhZJmfWCbBBSBk)

I think there may be a problem with your installation process.

**Comment by iagorm** [comment]
Thanks, it works like a charm! My camera isn`t showing, there is something I can do to make it work? The bright level also isn`t working.

**Comment by xzhih** [comment]
My camera works fine. 

Fix the cache with Kext Utility, may make the bright work.

**Comment by iagorm** [comment]
Now It works! Thanks @xzhih , now you can close this issue.
