### ISSUE TITLE
Screen goes black on hdmi connection

### ISSUE THREAD

**Issue by iagorm** [xzhih/dell-7460-7560-hackintosh#16]
The screen is going black when I plug the HDMI cable, and it never goes back.

**Comment by xzhih** [comment]
Enable HiDPI may help, try my script [here](https://github.com/xzhih/one-key-hidpi).

**Comment by xzhih** [comment]
Select first option to enable, Inspiron 7560 doesn't need to inject patches.

**Comment by iagordevsquad** [comment]
I installed this script, the fake retina is working, to logo is big on boot but the HDMI still doesn't work.

**Comment by iagordevsquad** [comment]
I installed again and the issue still exists, the laptop screen goes black and never show anything even unplugging the HDMI, My choice on install was 1->3->1.

**Comment by xzhih** [comment]
#10 Someone here said that it is working, mine too.

What your macOS version?  Upgrade to 10.13.5 may help. Maybe, I am not sure.

**Comment by iagordevsquad** [comment]
I'm in the version of .dmg(10.13.4). I can download this version directly on apple webpage? Sorry I'm new on hackintosh.

**Comment by iagordevsquad** [comment]
I updated directly by app store. Fixed the issue, was the refresh rate that was set to 60hz and it is default of my screen, when I changed, the laptop unlocked and showed the extended screen! Now everything works perfect, thank again @xzhih, can close the issue.
