### ISSUE TITLE
Headphone Jack doesn't work

### ISSUE THREAD

**Issue by iagorm** [xzhih/dell-7460-7560-hackintosh#17]
The headphone jack plug doesn't work, maybe there is any solution for that?

**Comment by xzhih** [comment]
Download the ALCPlugFix folder and double-click install... to run, you can solve the problem of silent wakeup, silent headphones, and headphones noise.

**Comment by iagordevsquad** [comment]
that one install双击自动卸载ALCPlugFix ? I installed, reboot and still not working, but in the sound devices it listen to changes to headphone, but still on silent

**Comment by iagordevsquad** [comment]
Oh was the install双击自动安装 to install the fix, can close the issue.
