### ISSUE TITLE
Wifi does not work, but bluetooth does

### ISSUE THREAD

**Issue by iagordevsquad** [xzhih/dell-7460-7560-hackintosh#18]
The Wifi ins't appearing in task bar, either in network settings, just ethernet and bluetooth, both of them works but wifi don't. The Wlan chipset is DW1820, there is something to do in that case?

**Comment by xzhih** [comment]
DW1820 does not work well under MacOS, DW1830/DW1560 is perfect.

**Comment by iagorm** [comment]
Perfect @xzhih, can close this issue
