### ISSUE TITLE
Loop apple logo, on latest EFI 10.13  [Dell 7572]

### ISSUE THREAD

**Issue by indraAsLesmana** [xzhih/dell-7460-7560-hackintosh#20]
your latest "Commits on Aug 3, 2018" not work my laptop 7572. On Jun 23, 2018 its work.

**Comment by xzhih** [comment]
What OS version? I passed the test on 10.13.6.

**Comment by indraAsLesmana** [comment]
yes its 10.13.6, I follow your guide on youtube with start image from 10.13.4.

**Comment by xzhih** [comment]
Try the detailed (-v) mode and find out what the error is.

**Comment by indraAsLesmana** [comment]
https://drive.google.com/open?id=1ivBBfp-PWcjTZa9FDDbQ5BU8DxsVSuEl

**Comment by xzhih** [comment]
try the new push, But I can't guarantee that it will solve your problem.

**Comment by indraAsLesmana** [comment]
Many thanks for you @xzhih , for your attention. I tried but it doesn't work. its still loop on apple logo.
maybe I'm wrong step installation, this is my please correct me if I'm wrong in this step :
1. open EFI with EFI Mounter v3.
2. Copy your latest EFI to partition EFI.
3. Update with running Kext Utility.
4. restart twice but still, loop on Apple logo. :)

Another problem "Commit On Jun 23, 2018" 
1. Brightness is not saved when restarting.
2. High Cpu usage eat by service  "Kernel_task" (cannot kill this service with Monitor.app, to solve must sleep laptop at first start)
3. "YaraService" this service eat all RAM when starting the laptop, but it can kill via Monitor.app

Thanks.

**Comment by xzhih** [comment]
Yours is the right step, but I don't know why there is a problem.

try to install clover yourself, [here is the latest clover](https://github.com/Dids/clover-builder/releases), and check EmuVariableUefi-64.efi in the driver option, this may fix the Brightness Save problem.

I have no idea about the 'Kernel_task' and 'YaraService' problem, I have never met.

Logo scaling up may not be resolved, cuz the higher resolution is faked.

**Comment by xyz60552** [comment]
@dayhi 请问您还有6🈷23日之前的EFI吗？能否发一下，谢谢。

**Comment by indraAsLesmana** [comment]
@dayhi @xyz60552 you can my EFI: https://goo.gl/7hzWVM

if you want sound work just replace AppleALC kext to version 1.2.8.
but issue with AppleALC 1.2.8, is cpu idle always on 2ghz.

**Comment by xzhih** [comment]
I have pushed the latest.

**Comment by indraAsLesmana** [comment]
@xzhih thanks.. this issue has fixed.

**Comment by miichelaguiar** [comment]
Battery Status does not update. Can someone fix me? Thank you!
