### ISSUE TITLE
Bad trackpad experience

### ISSUE THREAD

**Issue by BrunoGM** [xzhih/dell-7460-7560-hackintosh#24]
The trackpad of this notebook works much better with Windows or Linux, do you plan on making the trackpad experience better? There is a guy from tonymacx86 that patched his DSDT to support VoodooI2C & VoodooI2CHID kexts and it made the experience a lot better. I even tryed to combine your Clover with his DSDT/kexts but I couldn't put it to work(to many bugs). You can check the tonymacx86 post here: https://www.tonymacx86.com/threads/guide-dell-inspiron-7560-high-sierra-installation.242174/

Ps: I have beeing using your Build for months now and it's working greatly, it's very stable and has almost no bugs. Thank you for the hard work.

**Comment by xzhih** [comment]
PS2 mode is stable and reliable.
The kext I use has a lot of gestures, look [here](https://zhih.me/dell-7460-7560-hackintosh/#5-%E8%A7%A6%E6%91%B8%E6%9D%BF%E6%89%8B%E5%8A%BF).

You may need [this app](https://mos.caldis.me/) to enable smooth scrolling.

**Comment by BrunoGM** [comment]
The smooth scrolling software made it a little better but it is still nowhere near windows experience.

**Comment by xzhih** [comment]
Magic Trackpad is the best choose, this is hackintosh, the touchpad is not a native driver, and the experience can’t be compared to Windows.

**Comment by BrunoGM** [comment]
Yeah, that's right, but still, using an I2C kext can make it a lot better.

**Comment by xzhih** [comment]
I2C now.
