### ISSUE TITLE
请问 戴尔燃7000II-7472 使用最新的efi 无限重启怎么解决？

### ISSUE THREAD

**Issue by Eplayed** [xzhih/dell-7460-7560-hackintosh#25]
2018/9/8,按照教程折腾电脑，安装完后需u盘引导进入系统，根据视频教程设置默认启动，出苹果logo,出进度条，大约65% 黑屏，无限这个模式。系统版本是10.13.14，请问怎么解决？ 感谢！

**Comment by xzhih** [comment]
装 10.13.6，或者使用这个 EFI https://github.com/xzhih/dell-7460-7560-hackintosh/tree/03a3a280c4107a22c645f5373f165360b2c7cbbf

**Comment by Eplayed** [comment]
谢谢，问题解决了！还有个小问题，就是按键修饰建设置后无效，请问有解决办法吗？

**Comment by xzhih** [comment]
修饰建设置无效我倒是没遇到过，不过可以修改ps2键盘驱动的按键映射解决
