### ISSUE TITLE
最新的EFI 文件在10.14里的会出现卡在苹果图标页面

### ISSUE THREAD

**Issue by NathanDai** [xzhih/dell-7460-7560-hackintosh#27]
最新的EFI 文件在10.14里的会出现卡在苹果图标页面,但是10.13进10.13的页面是正常的,但是回滚到后两个版本的
 efi 可以正常使用,但是会出现无法识别笔记本自身的触控板,但是白苹果的触控板可以正常识别,我的设备的 dell-7460,已经把网卡换成 DW1560

**Comment by xzhih** [comment]
开啰嗦模式看log卡在哪里

**Comment by NathanDai** [comment]
start finalizebootstruct
start randomseed
end randomseed
+++++++++++++++++

**Comment by jmluang** [comment]
10.13.6无法使用。同是这个问题，到这里就直接重启了～
