### ISSUE TITLE
7472的HD620核显被识别为HD655

### ISSUE THREAD

**Issue by Howard-00** [xzhih/dell-7460-7560-hackintosh#28]
如果不管，会不会对性能有什么不良影响，如果会，应该怎么修改

**Comment by xzhih** [comment]
这是故意设置的，你可以在config里找到相关表单删除，包括显存部分，只是显示出这样，不会对使用造成影响，显存这样设置也可能会修补某些问题，总之是无害的

**Comment by Howard-00** [comment]
感谢作者耐心说明
