### ISSUE TITLE
卡死问题

### ISSUE THREAD

**Issue by hunao0221** [xzhih/dell-7460-7560-hackintosh#3]
用了一两天后出现了卡死问题， 比如qq截图，播放视频，音乐，Chrome打开设置等等操作时，会直接卡死，只有鼠标能用。 一旦出现这种情况后， 会一直存在，重启之后也不管用，初步怀疑是显卡驱动问题，请问有解决方法吗？

**Comment by xzhih** [comment]
应该是只有你一个人遇到了，可能是EFI不适合你，需要你自己配置了
