### ISSUE TITLE
换哪款网卡性价比最高

### ISSUE THREAD

**Issue by Howard-00** [xzhih/dell-7460-7560-hackintosh#30]

**Comment by xzhih** [comment]
不知道你加群了没有，最近群里讨论原装卡比较激烈，有点动手能力就搞转接卡+原装卡，稳定又好用，其次就买 dw1560、dw1830 咯，不过这两张卡都比较贵，现在被炒的感觉不划算了，如果只是将就用1707似乎可以用，好像只要18快吧，不过稳定性可能不佳

**Comment by xzhih** [comment]
群号:158976808
