### ISSUE TITLE
Bluetooth not working, Trackpad prefPane blank and hiDPI not working in Mojave

### ISSUE THREAD

**Issue by rbs7** [xzhih/dell-7460-7560-hackintosh#31]
When I installed Mojave (final version), bluetooth is not working (DW1560). It is not showing in System Information and also not showing in USB section.
Trackpad prefPane is blank in System Preferences.
Had to uninstall HiDPI because my screen got bad image after installation.
My laptop is a Dell 7472

**Comment by rbs7** [comment]
Today I modified VoodooPS2Controller.kext comparing with the latest version by RehabMan and Trackpad prefPane is back.
I tried HiDPI without patch and it worked, but I wasn't able to get the 2k resolution.
Bluetooth with DW1560 is still not working, neither in 10.13.6.

**Comment by rbs7** [comment]
I tried another bluetooth module and bluetooth is back

**Comment by Staby2000** [comment]
bluetooth is not working too
