### ISSUE TITLE
触控板一直无法正常工作

### ISSUE THREAD

**Issue by NJAUCRC** [xzhih/dell-7460-7560-hackintosh#38]
机型：Inspiron 14 7460
CPU：i7-7500U
内存：1x8GB DDR4 2400MHz
硬盘：SATA3 240GB SSD / M.2 SATA3 128GB SSD
声卡：ALC 3246
网卡：BCM94360CS2
（除更换网卡和固态硬盘外未进行其他改动）

故障描述：
使用该EFI安装系统并使用。严格按照所提供的教程进行快捷键和其他配置。但**系统偏好设置**中的**触控板**设置打开后显示空白。经测试，触控板仅双指滚动和三指轻扫功能可用。
根据先前 @rbs7 提问中给出的方法，尝试安装最新版VoodooPS2Controller.kext。安装并重新进行键位设置后触控板设置显示正常。多指触控依旧失灵，仅双指滚动功能可用。
此外，在使用Scroll Reverser、Mos等软件更改鼠标滚动方向时，发现触控板的滚动方向会和鼠标方向相同，无法分开单独设定。

涉及EFI版本：从2018-09-15到2018-11-15的所有10.14 EFI。
涉及系统版本：macOS Mojave 10.14(18A389)，macOS Mojave 10.14(18A391)，macOS Mojave 10.14.1(18B75)。

**Comment by xzhih** [comment]
首先，我 EFI 里使用的触控板驱动，不能在系统设置里进行设置，因为是使用的按键映射，所以去看看我博客里的 EFI 说明，设置快捷键，就能手势操作。所以我就没管什么设置页面空白的了。

另外，对触控板要求高的，请去使用 I2C 驱动，那个驱动很好用，但是有时会造成键盘失去响应。
