### ISSUE TITLE
请问如何让内建麦克风可用

### ISSUE THREAD

**Issue by qijianchao** [xzhih/dell-7460-7560-hackintosh#39]
我7460装完后很完美，但是声音设置里面默认输入是线性输入什么的，不是内建麦克风，程序需要调麦克风时候就会失败，但有一次不知道为什么突然显示输入是内建，立刻试了一下，可以录音，但是重启后又变了，需要怎么设置

**Comment by xzhih** [comment]
打音频守护补丁啊

**Comment by qijianchao** [comment]
是黑果小兵ALCfix吗那个吗？

**Comment by xzhih** [comment]
是的
