### ISSUE TITLE
多指触控问题

### ISSUE THREAD

**Issue by JackThinking** [xzhih/dell-7460-7560-hackintosh#4]
冰水你好，我用那你的efi完成了系统的安装和使用，其他的都很好，但是触控板的多指操作有一点问题，单指和双指都是正常的，但是三只和四只和你readme说的操作不同，我这边四只上划是关闭，四指下滑是最小化，三指上是隐藏dock，三指下是程序切换。

**Comment by xzhih** [comment]
注意看触控手势的相关说明，在快捷键里设置键位，和说明里的快捷键设置一样就可以了，手势其实是调用了快捷键
