### ISSUE TITLE
14版本WiFi连接2.4G频率，屏幕一直闪屏呢，136版本完美

### ISSUE THREAD

**Issue by SSflyme** [xzhih/dell-7460-7560-hackintosh#42]

**Comment by xzhih** [comment]
我没升级，还在 10.13.6

**Comment by SSflyme** [comment]
哦哦，我升级了，13.6用得很完美




    


在2018年12月11日 22:08，ZeRo Xu 写道： 我没升级，还在 10.13.6

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/xzhih/dell-7460-7560-hackintosh","title":"xzhih/dell-7460-7560-hackintosh","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/xzhih/dell-7460-7560-hackintosh"}},"updates":{"snippets":[{"icon":"PERSON","message":"@xzhih in #42: 我没升级，还在 10.13.6"}],"action":{"name":"View Issue","url":"https://github.com/xzhih/dell-7460-7560-hackintosh/issues/42#issuecomment-446214591"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/xzhih/dell-7460-7560-hackintosh/issues/42#issuecomment-446214591",
"url": "https://github.com/xzhih/dell-7460-7560-hackintosh/issues/42#issuecomment-446214591",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [xzhih/dell-7460-7560-hackintosh] 14版本WiFi连接2.4G频率，屏幕一直闪屏呢，136版本完美 (#42)",
"sections": [
{
"text": "",
"activityTitle": "**ZeRo Xu**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@xzhih",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"xzhih/dell-7460-7560-hackintosh\",\n\"issueId\": 42,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"xzhih/dell-7460-7560-hackintosh\",\n\"issueId\": 42\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/xzhih/dell-7460-7560-hackintosh/issues/42#issuecomment-446214591"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 422956695\n}"
}
],
"themeColor": "26292E"
}
]
