### ISSUE TITLE
10.14版本的CLOVER驱动中为什么缺少ACPIBatteryManager.kext

### ISSUE THREAD

**Issue by fanvinga** [xzhih/dell-7460-7560-hackintosh#45]
如题.是因为不需要了吗

**Comment by xzhih** [comment]
用了 VirtualSMC

**Comment by fanvinga** [comment]
看到了VirtualSMC.kext但是Driver64UEFI里面没有VirtualSMC.efi以及KEXT里面也没有SMCBatteryManager.kext啊😂

**Comment by xzhih** [comment]
打包在 VirtualSMC 的 Plugin 里了
