### ISSUE TITLE
默认键位绑定

### ISSUE THREAD

**Issue by ttttmr** [xzhih/dell-7460-7560-hackintosh#5]
你好，请问你的win->cmd，alt->opt的绑定是在哪里做的，貌似不是在设置里，是打了补丁吗

不太习惯你的设置😂，想换回原生的，要怎么操作（除了改设置，强迫症想直接复原）

**Comment by xzhih** [comment]
这些我都没动的，你要自己设置的，在，系统偏好设置->修饰键

**Comment by ttttmr** [comment]
好的吧，但是它默认win->cmd，alt->opt，而不是win->opt，alt->cmd，和我之前用的配置不一样😂
