### ISSUE TITLE
Bluetooth wake from Sleep

### ISSUE THREAD

**Issue by raphcrf** [xzhih/dell-7460-7560-hackintosh#51]
Hey there, how's it going?

Do you have any idea on how to fix the Bluetooth on wake?

Mine sometimes gets unavailable after notebook wakes up.

Thanks!

**Comment by xzhih** [comment]
Intel NIC has some problems, so I changed it to dw1560, Bluetooth and wifi are working very well now.

**Comment by raphcrf** [comment]
Hey there, thank you for the fast reply. I'm actually using dw1560. 
I was able to solve the issue by adding 3 bootflags: 
bpr_probedelay=300
bpr_initialdelay=500
bpr_postresetdelay=500

Hope that helps someone else.
