### ISSUE TITLE
Bluetooth dw1560 don't work

### ISSUE THREAD

**Issue by diegudias** [xzhih/dell-7460-7560-hackintosh#58]
I change to dw1560 wifi and bluetooth, but bluetooth don't work, don't show in the settings.

**Comment by xzhih** [comment]
delete USBPorts.kext and rebuild cache

**Comment by diegudias** [comment]
It worked. Thank you very much. Just one more question, removing the USBPorts.kext will stop working something?

**Comment by xzhih** [comment]
you can make it yourself by hackintool, it can fix some usb issues like can't sleep.

https://www.insanelymac.com/forum/topic/335018-hackintool-v204/
