### ISSUE TITLE
蓝牙无法关闭

### ISSUE THREAD

**Issue by ttttmr** [xzhih/dell-7460-7560-hackintosh#6]
蓝牙开机自启，而且关闭蓝牙是灰的😂是我操作不对吗😂

![image](https://user-images.githubusercontent.com/32825326/37266763-6ddec47e-25f7-11e8-8c9f-3e213b09fe9d.png)

**Comment by xzhih** [comment]
自带那张网卡吗？那个本来就驱动不全，换网卡吧，这问题我解决不了

**Comment by ttttmr** [comment]
没救了啊？那...能不能把驱动禁掉？不知道哪个是蓝牙的驱动😂

**Comment by xzhih** [comment]
他这个蓝牙驱动是系统内自动识别的，要屏蔽只能屏蔽接口了

**Comment by ttttmr** [comment]
好的，谢谢了
