### ISSUE TITLE
macOS 10.14 Successfully Installed but Cannot Booting with Clover (Dell 7472)

### ISSUE THREAD

**Issue by petrukngantuk** [xzhih/dell-7460-7560-hackintosh#60]
Hello,
I'm using your Clover Config for my hackintosh in my new laptop dell 7472, it's not working in booting, 
I think it's probably because the clover not detect the nvme driver,
I'm using ssd -> SN520 NVMe WDC 128gb (Built in when buying my new laptop dell 7472)

why i'm stating this, because when I'm using your config in my old laptop Dell 7460, it's work fine,

little research, in dell 7460 it's not using nvme...

I'm research about apfs.efi, apfsdriverloader-6.efi, nvmexpressdxe-64.efi, the clover it's not showing up the booting, even when I using clover from my flasdisk,

next n last, I installed high sierra 10.13.6, it's work perfectly fine, so... what's wrong?

any solution bro?

**Comment by xzhih** [comment]
Can it upgrade from 10.13.6 to 10.14?

**Comment by petrukngantuk** [comment]
> Can it upgrade from 10.13.6 to 10.14?

I haven't tried it yet

**Comment by petrukngantuk** [comment]
hell yeah, it's worked, I updated 10.13.6 to 10.14.4 with App Store and Replace EFI with 10.14 form yours...
Thanks Bro...

**Comment by petrukngantuk** [comment]
hello, in 10.14 my trackpad not detected, voodoI2C not working? or update manually?

**Comment by petrukngantuk** [comment]
the trackpad is working, reboot many time...

huft,
next, the ALCPlugFix is not working, how to fix this? any source tutorial?

**Comment by xzhih** [comment]
Every time you upgrade the macos, you must rebuild cache.

[Combojack](https://github.com/hackintosh-stuff/ComboJack) is a good choose to repalce ALCPlugFix.

**Comment by petrukngantuk** [comment]
> Every time you upgrade the macos, you must rebuild cache.
> 
> [Combojack](https://github.com/hackintosh-stuff/ComboJack) is a good choose to repalce ALCPlugFix.

it's worked bro, thanks,

I want to your recommendation for dell wireless, between dw1830 / dw 1560 what's your recommendation bro?

**Comment by xzhih** [comment]
DW1830, dw1560 have become more and more expensive in the past two years.
So I think BCM94360CS2 is a good choose now, but need a conversion card.

BCM94360CS2 + conversion card only ￥60( about 9 USD).

![](https://ae01.alicdn.com/kf/HTB1J_xcSpXXXXb0XXXXq6xXFXXXN/New-BCM94360CS2-Wireless-AC-WIFI-Bluetooth-BT-4-0-Airport-802-11ac-Card-For-Macbook-Air.jpg)

![](https://gd4.alicdn.com/imgextra/i4/2933523049/TB2HiTxuDdYBeNkSmLyXXXfnVXa_!!2933523049.jpg_400x400.jpg)

If you can't easily buy these, dw1560 also a good choose, do not buy dw1830.

**Comment by petrukngantuk** [comment]
i just bought [this](https://www.ebay.com/itm/Dell-Wireless-1830-ABGNAC-WLAN-BT-NGFF-Card-BCM943602BAED-GKCG2-For-XPS-15-9550/282120771022?epid=1780183499&hash=item41afb555ce:g:XT4AAOSwCfdXpeEg&frcectupt=true)
it's working right?

anothe problem,
when I plug in the HDMI, the built-in display is blank out (black), but the extenal display it shown, when I check System Preferences -> Display, the two is shown Built-in Retina Display + LEN...(My Monitor), any ideas or link tutorial how to fix this?

**Comment by xzhih** [comment]
BCM943602BAED is working but not working well.

Close and open the lid, the built-in display will show.

**Comment by petrukngantuk** [comment]
> BCM943602BAED is working but not working well.
> 
> Close and open the lid, the built-in display will show.

any link for the buy in ebay? or alibaba?

**Comment by xzhih** [comment]
[BCM94360CS2](https://www.ebay.com/itm/Apple-MacBook-Air-13-A1466-Airport-Bluetooth-4-0-Card-BCM94360CS2AX-661-7481/132448231447?_trkparms=aid%3D555018%26algo%3DPL.SIM%26ao%3D1%26asc%3D57158%26meid%3Dc10d4ae084c04878a23c934f03481eb2%26pid%3D100005%26rk%3D6%26rkt%3D12%26sd%3D283111724041%26itm%3D132448231447&_trksid=p2047675.c100005.m1851)

[Conversion card](https://www.ebay.com/itm/BCM94360CS2-BCM943224PCIEBT2-4331-Card-To-NGFF-M-2-Key-A-E-Adapter-For-Mac-OS/282895100847?hash=item41dddcabaf:g:o04AAOSw-NFaw0j3)

**Comment by xzhih** [comment]
You can find other cheaper.

**Comment by petrukngantuk** [comment]
> Close and open the lid, the built-in display will show.
It's working well...



> [BCM94360CS2](https://www.ebay.com/itm/Apple-MacBook-Air-13-A1466-Airport-Bluetooth-4-0-Card-BCM94360CS2AX-661-7481/132448231447?_trkparms=aid%3D555018%26algo%3DPL.SIM%26ao%3D1%26asc%3D57158%26meid%3Dc10d4ae084c04878a23c934f03481eb2%26pid%3D100005%26rk%3D6%26rkt%3D12%26sd%3D283111724041%26itm%3D132448231447&_trksid=p2047675.c100005.m1851)
> 
> [Conversion card](https://www.ebay.com/itm/BCM94360CS2-BCM943224PCIEBT2-4331-Card-To-NGFF-M-2-Key-A-E-Adapter-For-Mac-OS/282895100847?hash=item41dddcabaf:g:o04AAOSw-NFaw0j3)

I Just bought [BCM94360CS2/ DW1830](https://www.ebay.com/itm/13-Macbook-Air-A1465-A1466-MD711-MD712-MD760-761-Bluetooth4-0-AirPort-WiFi-Card/281513533371?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2060353.m2749.l2649) and [Converter Card To NGFF](https://www.ebay.com/itm/BCM94360CS2-BCM943224PCIEBT2-4331-Card-To-NGFF-M-2-Key-A-E-Adapter-For-Mac-OS/282895100847?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2060353.m2749.l2649) 

No Problem again until now,
I will open this issue if other problem arises,

Thanks for your support, may this issue help other people want to install hackintosh in Dell 7472,

**Comment by petrukngantuk** [comment]
@xzhih  Hello my BCM94360CS2, sometime error, it's off on randomly for no reason,
do you know how to fix this?

**Comment by xzhih** [comment]
Attention insulation
