### ISSUE TITLE
random shutdown

### ISSUE THREAD

**Issue by Jucian0** [xzhih/dell-7460-7560-hackintosh#72]
I have bem instaled on my del 7560, but my laptop shutdown everytime

**Comment by xzhih** [comment]
Which version you have installed ?
Many people use this EFI, and everything is fine.

**Comment by Jucian0** [comment]
now everything is fine, shutdown happened when I was instaling on my SSD, but now I have instaled on HD and its fine. I think it´s a problem in my SSD.
