### ISSUE TITLE
10.15.4系统版本下,使用10.15的efi无法进入系统

### ISSUE THREAD

**Issue by ryan255** [xzhih/dell-7460-7560-hackintosh#75]
我自己尝试更新了lilu和whatevergreen版本解决. 但是不太完美,核显能驱动但是显存由以前的2GB变成1.5GB了. 而且不支持H265硬解.

**Comment by xzhih** [comment]
10.15.4 需要更新 clover，别的到没什么要改

我的燃已经报废，这个仓库不再维护
