### ISSUE TITLE
Using the original image *Sierra* 

### ISSUE THREAD

**Issue by HydroRifle** [xzhih/dell-7460-7560-hackintosh#8]
I just saw your github page which introduces a way to install OS X on my inspiron 14 7472.
(i5-8250u/MX150)
It says that I shall restore it with tranmac, but how should I deal with the image downloaded from AppStore? maybe I should just download another modified image ?

Best Regards

**Comment by XuToTo** [comment]
I have never tried the original image , but if u dont mind, [here](https://blog.daliansky.net/macOS-High-Sierra-10.13.3-(17D47)-official-version-and-Clover-4391-original-image.html) blog u could find download links of modified image which has integrated Clover.

btw:
我一代用大大默认的配置文件，加载无限重启 :cry:

**Comment by xzhih** [comment]
Transmac is used under Win. If U have Mac, don't need it.
This is a tutorial for making boot disk under Mac, from apple.
[https://support.apple.com/zh-cn/HT201372](https://support.apple.com/zh-cn/HT201372)

@XuToTo has already post a download address, which is used in Win, and uses Transmac.

@daliansky [黑果小兵的部落格](blog.daliansky.net) There are some tutorials in this blog. You may need to know about them.  [https://www.tonymacx86.com](https://www.tonymacx86.com) is also a good choice.
